### ISSUE TITLE
Setting Custom Hotkey doesn't work in Safari extension

### ISSUE THREAD

**Issue by mliq** [canisbos/Pickpocket#8]
Thanks for the wonderful extension!

In the settings of the safari extension, I can type anything into the inputs for hotkeys, but it never changes the default hotkey.

macOS 10.12.4
Safari 10.1
Macbook Pro

**Comment by canisbos** [comment]
Hmm. It works on my machine. 

When you open the settings popup, are the settings populated or empty? Does each of the radio button groups have one option selected, or are all options deselected? Sometimes I have seen all of the settings unpopulated after installing the extension, which is due to an unknown bug. When the extension is in this bad state, none of the settings seem to save. Restarting Safari fixes it, if I remember correctly.

If you are able to change and save other settings, but not the hotkey, I can't reproduce that. Maybe try uninstalling and reinstalling the extension.

**Comment by mliq** [comment]
It turns out that it was (I think) because the Safari settings window was still open hiding in the background somewhere, all works now that I closed it, or perhaps it was restarting Safari. I did have the blank options initially as you say but they were saved when I changed them (except for the hotkey). All good now, thank you for the quick response!

**Comment by canisbos** [comment]
Ah, good.       
  
  
  
  
  

  
  
>
